version: '3.8'

services:
  web_service:
    image: company_profile:2.0.0
    ports:
      - target: 8080
        published: 10160
        mode: ingress
    environment:
      - ./source/storage/:/var/www/html/storage/
    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
        mode: non-blocking
