version: '3.8'

services:
  web_service:
    image: $IMAGE_REPO_NAME:$IMAGE_TAG
    ports:
      - target: 8080
        published: 10160
        protocol: tcp
        mode: ingress
    volumes:
      - ./source/storage/:/var/www/html/storage/
    environment:
      # Example of environment variables
      APP_ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
